// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.booking.domain;

import org.adorsys.geshotel.booking.domain.RoomCategoryDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RoomCategoryIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RoomCategoryIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RoomCategoryIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RoomCategoryIntegrationTest: @Transactional;
    
    @Autowired
    private RoomCategoryDataOnDemand RoomCategoryIntegrationTest.dod;
    
    @Test
    public void RoomCategoryIntegrationTest.testCountRoomCategorys() {
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", dod.getRandomRoomCategory());
        long count = org.adorsys.geshotel.booking.domain.RoomCategory.countRoomCategorys();
        org.junit.Assert.assertTrue("Counter for 'RoomCategory' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testFindRoomCategory() {
        org.adorsys.geshotel.booking.domain.RoomCategory obj = dod.getRandomRoomCategory();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.booking.domain.RoomCategory.findRoomCategory(id);
        org.junit.Assert.assertNotNull("Find method for 'RoomCategory' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RoomCategory' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testFindAllRoomCategorys() {
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", dod.getRandomRoomCategory());
        long count = org.adorsys.geshotel.booking.domain.RoomCategory.countRoomCategorys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RoomCategory', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.booking.domain.RoomCategory> result = org.adorsys.geshotel.booking.domain.RoomCategory.findAllRoomCategorys();
        org.junit.Assert.assertNotNull("Find all method for 'RoomCategory' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RoomCategory' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testFindRoomCategoryEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", dod.getRandomRoomCategory());
        long count = org.adorsys.geshotel.booking.domain.RoomCategory.countRoomCategorys();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.booking.domain.RoomCategory> result = org.adorsys.geshotel.booking.domain.RoomCategory.findRoomCategoryEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RoomCategory' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RoomCategory' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testFlush() {
        org.adorsys.geshotel.booking.domain.RoomCategory obj = dod.getRandomRoomCategory();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.booking.domain.RoomCategory.findRoomCategory(id);
        org.junit.Assert.assertNotNull("Find method for 'RoomCategory' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRoomCategory(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RoomCategory' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testMerge() {
        org.adorsys.geshotel.booking.domain.RoomCategory obj = dod.getRandomRoomCategory();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.booking.domain.RoomCategory.findRoomCategory(id);
        boolean modified =  dod.modifyRoomCategory(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.booking.domain.RoomCategory merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'RoomCategory' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", dod.getRandomRoomCategory());
        org.adorsys.geshotel.booking.domain.RoomCategory obj = dod.getNewTransientRoomCategory(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RoomCategory' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RoomCategory' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RoomCategoryIntegrationTest.testRemove() {
        org.adorsys.geshotel.booking.domain.RoomCategory obj = dod.getRandomRoomCategory();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RoomCategory' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.booking.domain.RoomCategory.findRoomCategory(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RoomCategory' with identifier '" + id + "'", org.adorsys.geshotel.booking.domain.RoomCategory.findRoomCategory(id));
    }
    
}
