// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.booking.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.adorsys.geshotel.booking.domain.RoomCategory;
import org.springframework.stereotype.Component;

privileged aspect RoomCategoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RoomCategoryDataOnDemand: @Component;
    
    private Random RoomCategoryDataOnDemand.rnd = new SecureRandom();
    
    private List<RoomCategory> RoomCategoryDataOnDemand.data;
    
    public RoomCategory RoomCategoryDataOnDemand.getNewTransientRoomCategory(int index) {
        RoomCategory obj = new RoomCategory();
        setDescription(obj, index);
        setPrice(obj, index);
        setPriceMin(obj, index);
        setTitle(obj, index);
        return obj;
    }
    
    public void RoomCategoryDataOnDemand.setDescription(RoomCategory obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void RoomCategoryDataOnDemand.setPrice(RoomCategory obj, int index) {
        BigDecimal price = BigDecimal.valueOf(index);
        obj.setPrice(price);
    }
    
    public void RoomCategoryDataOnDemand.setPriceMin(RoomCategory obj, int index) {
        BigDecimal priceMin = BigDecimal.valueOf(index);
        obj.setPriceMin(priceMin);
    }
    
    public void RoomCategoryDataOnDemand.setTitle(RoomCategory obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public RoomCategory RoomCategoryDataOnDemand.getSpecificRoomCategory(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        RoomCategory obj = data.get(index);
        return RoomCategory.findRoomCategory(obj.getId());
    }
    
    public RoomCategory RoomCategoryDataOnDemand.getRandomRoomCategory() {
        init();
        RoomCategory obj = data.get(rnd.nextInt(data.size()));
        return RoomCategory.findRoomCategory(obj.getId());
    }
    
    public boolean RoomCategoryDataOnDemand.modifyRoomCategory(RoomCategory obj) {
        return false;
    }
    
    public void RoomCategoryDataOnDemand.init() {
        data = RoomCategory.findRoomCategoryEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'RoomCategory' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.adorsys.geshotel.booking.domain.RoomCategory>();
        for (int i = 0; i < 10; i++) {
            RoomCategory obj = getNewTransientRoomCategory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
