// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.booking.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RoomCategoryDataOnDemand_Roo_Configurable {
    
    declare @type: RoomCategoryDataOnDemand: @Configurable;
    
}
