package org.adorsys.geshotel.domain;

public enum RoleName {

	ROLE_ADMIN, ROLE_MANAGER, ROLE_RECEPTION, ROLE_SALE_AGENT, ROLE_CASH_AGENT, ROLE_RESTO_MANAGER,
	ROLE_BARMAN,ROLE_KITCHEN_MANAGER,ROLE_HEAD_MANAGER,ROLE_HEAD_CUTTER
}