// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.adorsys.geshotel.resto.domain.BrTable;
import org.springframework.stereotype.Component;

privileged aspect BrTableDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BrTableDataOnDemand: @Component;
    
    private Random BrTableDataOnDemand.rnd = new SecureRandom();
    
    private List<BrTable> BrTableDataOnDemand.data;
    
    public BrTable BrTableDataOnDemand.getNewTransientBrTable(int index) {
        BrTable obj = new BrTable();
        setBrTableKey(obj, index);
        setDescription(obj, index);
        setTableNumber(obj, index);
        return obj;
    }
    
    public void BrTableDataOnDemand.setBrTableKey(BrTable obj, int index) {
        String brTableKey = "brTableKey_" + index;
        obj.setBrTableKey(brTableKey);
    }
    
    public void BrTableDataOnDemand.setDescription(BrTable obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void BrTableDataOnDemand.setTableNumber(BrTable obj, int index) {
        String tableNumber = "tableNumber_" + index;
        obj.setTableNumber(tableNumber);
    }
    
    public BrTable BrTableDataOnDemand.getSpecificBrTable(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        BrTable obj = data.get(index);
        return BrTable.findBrTable(obj.getId());
    }
    
    public BrTable BrTableDataOnDemand.getRandomBrTable() {
        init();
        BrTable obj = data.get(rnd.nextInt(data.size()));
        return BrTable.findBrTable(obj.getId());
    }
    
    public boolean BrTableDataOnDemand.modifyBrTable(BrTable obj) {
        return false;
    }
    
    public void BrTableDataOnDemand.init() {
        data = BrTable.findBrTableEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'BrTable' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.adorsys.geshotel.resto.domain.BrTable>();
        for (int i = 0; i < 10; i++) {
            BrTable obj = getNewTransientBrTable(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
