// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.BrTableDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BrTableIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BrTableIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BrTableIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BrTableIntegrationTest: @Transactional;
    
    @Autowired
    private BrTableDataOnDemand BrTableIntegrationTest.dod;
    
    @Test
    public void BrTableIntegrationTest.testCountBrTables() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", dod.getRandomBrTable());
        long count = org.adorsys.geshotel.resto.domain.BrTable.countBrTables();
        org.junit.Assert.assertTrue("Counter for 'BrTable' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BrTableIntegrationTest.testFindBrTable() {
        org.adorsys.geshotel.resto.domain.BrTable obj = dod.getRandomBrTable();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.BrTable.findBrTable(id);
        org.junit.Assert.assertNotNull("Find method for 'BrTable' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'BrTable' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BrTableIntegrationTest.testFindAllBrTables() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", dod.getRandomBrTable());
        long count = org.adorsys.geshotel.resto.domain.BrTable.countBrTables();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'BrTable', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.BrTable> result = org.adorsys.geshotel.resto.domain.BrTable.findAllBrTables();
        org.junit.Assert.assertNotNull("Find all method for 'BrTable' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'BrTable' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BrTableIntegrationTest.testFindBrTableEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", dod.getRandomBrTable());
        long count = org.adorsys.geshotel.resto.domain.BrTable.countBrTables();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.BrTable> result = org.adorsys.geshotel.resto.domain.BrTable.findBrTableEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'BrTable' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'BrTable' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BrTableIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.BrTable obj = dod.getRandomBrTable();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.BrTable.findBrTable(id);
        org.junit.Assert.assertNotNull("Find method for 'BrTable' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBrTable(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'BrTable' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BrTableIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.BrTable obj = dod.getRandomBrTable();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.BrTable.findBrTable(id);
        boolean modified =  dod.modifyBrTable(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.BrTable merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'BrTable' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BrTableIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", dod.getRandomBrTable());
        org.adorsys.geshotel.resto.domain.BrTable obj = dod.getNewTransientBrTable(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'BrTable' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'BrTable' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BrTableIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.BrTable obj = dod.getRandomBrTable();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BrTable' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.BrTable.findBrTable(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'BrTable' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.BrTable.findBrTable(id));
    }
    
}
