// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.CashRegisterDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CashRegisterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CashRegisterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CashRegisterIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CashRegisterIntegrationTest: @Transactional;
    
    @Autowired
    private CashRegisterDataOnDemand CashRegisterIntegrationTest.dod;
    
    @Test
    public void CashRegisterIntegrationTest.testCountCashRegisters() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", dod.getRandomCashRegister());
        long count = org.adorsys.geshotel.resto.domain.CashRegister.countCashRegisters();
        org.junit.Assert.assertTrue("Counter for 'CashRegister' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CashRegisterIntegrationTest.testFindCashRegister() {
        org.adorsys.geshotel.resto.domain.CashRegister obj = dod.getRandomCashRegister();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.CashRegister.findCashRegister(id);
        org.junit.Assert.assertNotNull("Find method for 'CashRegister' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CashRegister' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CashRegisterIntegrationTest.testFindAllCashRegisters() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", dod.getRandomCashRegister());
        long count = org.adorsys.geshotel.resto.domain.CashRegister.countCashRegisters();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CashRegister', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.CashRegister> result = org.adorsys.geshotel.resto.domain.CashRegister.findAllCashRegisters();
        org.junit.Assert.assertNotNull("Find all method for 'CashRegister' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CashRegister' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CashRegisterIntegrationTest.testFindCashRegisterEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", dod.getRandomCashRegister());
        long count = org.adorsys.geshotel.resto.domain.CashRegister.countCashRegisters();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.CashRegister> result = org.adorsys.geshotel.resto.domain.CashRegister.findCashRegisterEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CashRegister' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CashRegister' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CashRegisterIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.CashRegister obj = dod.getRandomCashRegister();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.CashRegister.findCashRegister(id);
        org.junit.Assert.assertNotNull("Find method for 'CashRegister' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCashRegister(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CashRegister' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CashRegisterIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.CashRegister obj = dod.getRandomCashRegister();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.CashRegister.findCashRegister(id);
        boolean modified =  dod.modifyCashRegister(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.CashRegister merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CashRegister' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CashRegisterIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", dod.getRandomCashRegister());
        org.adorsys.geshotel.resto.domain.CashRegister obj = dod.getNewTransientCashRegister(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CashRegister' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CashRegister' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CashRegisterIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.CashRegister obj = dod.getRandomCashRegister();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CashRegister' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.CashRegister.findCashRegister(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CashRegister' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.CashRegister.findCashRegister(id));
    }
    
}
