// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.DiscountDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DiscountIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DiscountIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DiscountIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DiscountIntegrationTest: @Transactional;
    
    @Autowired
    private DiscountDataOnDemand DiscountIntegrationTest.dod;
    
    @Test
    public void DiscountIntegrationTest.testCountDiscounts() {
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", dod.getRandomDiscount());
        long count = org.adorsys.geshotel.resto.domain.Discount.countDiscounts();
        org.junit.Assert.assertTrue("Counter for 'Discount' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DiscountIntegrationTest.testFindDiscount() {
        org.adorsys.geshotel.resto.domain.Discount obj = dod.getRandomDiscount();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.Discount.findDiscount(id);
        org.junit.Assert.assertNotNull("Find method for 'Discount' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Discount' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DiscountIntegrationTest.testFindAllDiscounts() {
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", dod.getRandomDiscount());
        long count = org.adorsys.geshotel.resto.domain.Discount.countDiscounts();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Discount', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.Discount> result = org.adorsys.geshotel.resto.domain.Discount.findAllDiscounts();
        org.junit.Assert.assertNotNull("Find all method for 'Discount' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Discount' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DiscountIntegrationTest.testFindDiscountEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", dod.getRandomDiscount());
        long count = org.adorsys.geshotel.resto.domain.Discount.countDiscounts();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.Discount> result = org.adorsys.geshotel.resto.domain.Discount.findDiscountEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Discount' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Discount' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DiscountIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.Discount obj = dod.getRandomDiscount();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.Discount.findDiscount(id);
        org.junit.Assert.assertNotNull("Find method for 'Discount' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDiscount(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Discount' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DiscountIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.Discount obj = dod.getRandomDiscount();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.Discount.findDiscount(id);
        boolean modified =  dod.modifyDiscount(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.Discount merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Discount' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DiscountIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", dod.getRandomDiscount());
        org.adorsys.geshotel.resto.domain.Discount obj = dod.getNewTransientDiscount(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Discount' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Discount' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DiscountIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.Discount obj = dod.getRandomDiscount();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Discount' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.Discount.findDiscount(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Discount' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.Discount.findDiscount(id));
    }
    
}
