// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import java.lang.Boolean;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.adorsys.geshotel.domain.UserAccount;
import org.adorsys.geshotel.domain.UserAccountDataOnDemand;
import org.adorsys.geshotel.resto.domain.BarRestauState;
import org.adorsys.geshotel.resto.domain.Inventory;
import org.adorsys.geshotel.resto.domain.PeriodConf;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect InventoryDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InventoryDataOnDemand: @Component;
    
    private Random InventoryDataOnDemand.rnd = new SecureRandom();
    
    private List<Inventory> InventoryDataOnDemand.data;
    
    @Autowired
    private UserAccountDataOnDemand InventoryDataOnDemand.userAccountDataOnDemand;
    
    public Inventory InventoryDataOnDemand.getNewTransientInventory(int index) {
        Inventory obj = new Inventory();
        setInventoryDate(obj, index);
        setInventoryState(obj, index);
        setIsClosed(obj, index);
        setPeriodConf(obj, index);
        setTitle(obj, index);
        setUserAccount(obj, index);
        return obj;
    }
    
    public void InventoryDataOnDemand.setInventoryDate(Inventory obj, int index) {
        Date inventoryDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setInventoryDate(inventoryDate);
    }
    
    public void InventoryDataOnDemand.setInventoryState(Inventory obj, int index) {
        BarRestauState inventoryState = BarRestauState.class.getEnumConstants()[0];
        obj.setInventoryState(inventoryState);
    }
    
    public void InventoryDataOnDemand.setIsClosed(Inventory obj, int index) {
        Boolean isClosed = Boolean.TRUE;
        obj.setIsClosed(isClosed);
    }
    
    public void InventoryDataOnDemand.setPeriodConf(Inventory obj, int index) {
        PeriodConf periodConf = null;
        obj.setPeriodConf(periodConf);
    }
    
    public void InventoryDataOnDemand.setTitle(Inventory obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public void InventoryDataOnDemand.setUserAccount(Inventory obj, int index) {
        UserAccount userAccount = userAccountDataOnDemand.getRandomUserAccount();
        obj.setUserAccount(userAccount);
    }
    
    public Inventory InventoryDataOnDemand.getSpecificInventory(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Inventory obj = data.get(index);
        return Inventory.findInventory(obj.getId());
    }
    
    public Inventory InventoryDataOnDemand.getRandomInventory() {
        init();
        Inventory obj = data.get(rnd.nextInt(data.size()));
        return Inventory.findInventory(obj.getId());
    }
    
    public boolean InventoryDataOnDemand.modifyInventory(Inventory obj) {
        return false;
    }
    
    public void InventoryDataOnDemand.init() {
        data = Inventory.findInventoryEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Inventory' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.adorsys.geshotel.resto.domain.Inventory>();
        for (int i = 0; i < 10; i++) {
            Inventory obj = getNewTransientInventory(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
