// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.KitchenOrderItemDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect KitchenOrderItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: KitchenOrderItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: KitchenOrderItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: KitchenOrderItemIntegrationTest: @Transactional;
    
    @Autowired
    private KitchenOrderItemDataOnDemand KitchenOrderItemIntegrationTest.dod;
    
    @Test
    public void KitchenOrderItemIntegrationTest.testCountKitchenOrderItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", dod.getRandomKitchenOrderItem());
        long count = org.adorsys.geshotel.resto.domain.KitchenOrderItem.countKitchenOrderItems();
        org.junit.Assert.assertTrue("Counter for 'KitchenOrderItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testFindKitchenOrderItem() {
        org.adorsys.geshotel.resto.domain.KitchenOrderItem obj = dod.getRandomKitchenOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.KitchenOrderItem.findKitchenOrderItem(id);
        org.junit.Assert.assertNotNull("Find method for 'KitchenOrderItem' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'KitchenOrderItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testFindAllKitchenOrderItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", dod.getRandomKitchenOrderItem());
        long count = org.adorsys.geshotel.resto.domain.KitchenOrderItem.countKitchenOrderItems();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'KitchenOrderItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.KitchenOrderItem> result = org.adorsys.geshotel.resto.domain.KitchenOrderItem.findAllKitchenOrderItems();
        org.junit.Assert.assertNotNull("Find all method for 'KitchenOrderItem' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'KitchenOrderItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testFindKitchenOrderItemEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", dod.getRandomKitchenOrderItem());
        long count = org.adorsys.geshotel.resto.domain.KitchenOrderItem.countKitchenOrderItems();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.KitchenOrderItem> result = org.adorsys.geshotel.resto.domain.KitchenOrderItem.findKitchenOrderItemEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'KitchenOrderItem' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'KitchenOrderItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.KitchenOrderItem obj = dod.getRandomKitchenOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.KitchenOrderItem.findKitchenOrderItem(id);
        org.junit.Assert.assertNotNull("Find method for 'KitchenOrderItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyKitchenOrderItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'KitchenOrderItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.KitchenOrderItem obj = dod.getRandomKitchenOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.KitchenOrderItem.findKitchenOrderItem(id);
        boolean modified =  dod.modifyKitchenOrderItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.KitchenOrderItem merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'KitchenOrderItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", dod.getRandomKitchenOrderItem());
        org.adorsys.geshotel.resto.domain.KitchenOrderItem obj = dod.getNewTransientKitchenOrderItem(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'KitchenOrderItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'KitchenOrderItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void KitchenOrderItemIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.KitchenOrderItem obj = dod.getRandomKitchenOrderItem();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'KitchenOrderItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.KitchenOrderItem.findKitchenOrderItem(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'KitchenOrderItem' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.KitchenOrderItem.findKitchenOrderItem(id));
    }
    
}
