// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.adorsys.geshotel.resto.domain.ParentGroup;
import org.springframework.stereotype.Component;

privileged aspect ParentGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParentGroupDataOnDemand: @Component;
    
    private Random ParentGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<ParentGroup> ParentGroupDataOnDemand.data;
    
    public ParentGroup ParentGroupDataOnDemand.getNewTransientParentGroup(int index) {
        ParentGroup obj = new ParentGroup();
        setDescription(obj, index);
        setParentGroupKey(obj, index);
        setProductGroupKey(obj, index);
        setProductGroupParentKey(obj, index);
        return obj;
    }
    
    public void ParentGroupDataOnDemand.setDescription(ParentGroup obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ParentGroupDataOnDemand.setParentGroupKey(ParentGroup obj, int index) {
        String parentGroupKey = "parentGroupKey_" + index;
        obj.setParentGroupKey(parentGroupKey);
    }
    
    public void ParentGroupDataOnDemand.setProductGroupKey(ParentGroup obj, int index) {
        String productGroupKey = "productGroupKey_" + index;
        obj.setProductGroupKey(productGroupKey);
    }
    
    public void ParentGroupDataOnDemand.setProductGroupParentKey(ParentGroup obj, int index) {
        String productGroupParentKey = "productGroupParentKey_" + index;
        obj.setProductGroupParentKey(productGroupParentKey);
    }
    
    public ParentGroup ParentGroupDataOnDemand.getSpecificParentGroup(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        ParentGroup obj = data.get(index);
        return ParentGroup.findParentGroup(obj.getId());
    }
    
    public ParentGroup ParentGroupDataOnDemand.getRandomParentGroup() {
        init();
        ParentGroup obj = data.get(rnd.nextInt(data.size()));
        return ParentGroup.findParentGroup(obj.getId());
    }
    
    public boolean ParentGroupDataOnDemand.modifyParentGroup(ParentGroup obj) {
        return false;
    }
    
    public void ParentGroupDataOnDemand.init() {
        data = ParentGroup.findParentGroupEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'ParentGroup' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.adorsys.geshotel.resto.domain.ParentGroup>();
        for (int i = 0; i < 10; i++) {
            ParentGroup obj = getNewTransientParentGroup(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
