// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.ParentGroupDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParentGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParentGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParentGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ParentGroupIntegrationTest: @Transactional;
    
    @Autowired
    private ParentGroupDataOnDemand ParentGroupIntegrationTest.dod;
    
    @Test
    public void ParentGroupIntegrationTest.testCountParentGroups() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", dod.getRandomParentGroup());
        long count = org.adorsys.geshotel.resto.domain.ParentGroup.countParentGroups();
        org.junit.Assert.assertTrue("Counter for 'ParentGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParentGroupIntegrationTest.testFindParentGroup() {
        org.adorsys.geshotel.resto.domain.ParentGroup obj = dod.getRandomParentGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ParentGroup.findParentGroup(id);
        org.junit.Assert.assertNotNull("Find method for 'ParentGroup' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ParentGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParentGroupIntegrationTest.testFindAllParentGroups() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", dod.getRandomParentGroup());
        long count = org.adorsys.geshotel.resto.domain.ParentGroup.countParentGroups();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ParentGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.ParentGroup> result = org.adorsys.geshotel.resto.domain.ParentGroup.findAllParentGroups();
        org.junit.Assert.assertNotNull("Find all method for 'ParentGroup' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ParentGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParentGroupIntegrationTest.testFindParentGroupEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", dod.getRandomParentGroup());
        long count = org.adorsys.geshotel.resto.domain.ParentGroup.countParentGroups();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.ParentGroup> result = org.adorsys.geshotel.resto.domain.ParentGroup.findParentGroupEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ParentGroup' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ParentGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParentGroupIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.ParentGroup obj = dod.getRandomParentGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ParentGroup.findParentGroup(id);
        org.junit.Assert.assertNotNull("Find method for 'ParentGroup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParentGroup(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ParentGroup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParentGroupIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.ParentGroup obj = dod.getRandomParentGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ParentGroup.findParentGroup(id);
        boolean modified =  dod.modifyParentGroup(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.ParentGroup merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ParentGroup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParentGroupIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", dod.getRandomParentGroup());
        org.adorsys.geshotel.resto.domain.ParentGroup obj = dod.getNewTransientParentGroup(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ParentGroup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ParentGroup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParentGroupIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.ParentGroup obj = dod.getRandomParentGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ParentGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ParentGroup.findParentGroup(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ParentGroup' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.ParentGroup.findParentGroup(id));
    }
    
}
