// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.ProductGroupDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProductGroupIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductGroupIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductGroupIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ProductGroupIntegrationTest: @Transactional;
    
    @Autowired
    private ProductGroupDataOnDemand ProductGroupIntegrationTest.dod;
    
    @Test
    public void ProductGroupIntegrationTest.testCountProductGroups() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", dod.getRandomProductGroup());
        long count = org.adorsys.geshotel.resto.domain.ProductGroup.countProductGroups();
        org.junit.Assert.assertTrue("Counter for 'ProductGroup' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductGroupIntegrationTest.testFindProductGroup() {
        org.adorsys.geshotel.resto.domain.ProductGroup obj = dod.getRandomProductGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ProductGroup.findProductGroup(id);
        org.junit.Assert.assertNotNull("Find method for 'ProductGroup' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'ProductGroup' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductGroupIntegrationTest.testFindAllProductGroups() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", dod.getRandomProductGroup());
        long count = org.adorsys.geshotel.resto.domain.ProductGroup.countProductGroups();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'ProductGroup', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.ProductGroup> result = org.adorsys.geshotel.resto.domain.ProductGroup.findAllProductGroups();
        org.junit.Assert.assertNotNull("Find all method for 'ProductGroup' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'ProductGroup' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductGroupIntegrationTest.testFindProductGroupEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", dod.getRandomProductGroup());
        long count = org.adorsys.geshotel.resto.domain.ProductGroup.countProductGroups();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.ProductGroup> result = org.adorsys.geshotel.resto.domain.ProductGroup.findProductGroupEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'ProductGroup' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'ProductGroup' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductGroupIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.ProductGroup obj = dod.getRandomProductGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ProductGroup.findProductGroup(id);
        org.junit.Assert.assertNotNull("Find method for 'ProductGroup' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductGroup(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'ProductGroup' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductGroupIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.ProductGroup obj = dod.getRandomProductGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ProductGroup.findProductGroup(id);
        boolean modified =  dod.modifyProductGroup(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.ProductGroup merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'ProductGroup' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductGroupIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", dod.getRandomProductGroup());
        org.adorsys.geshotel.resto.domain.ProductGroup obj = dod.getNewTransientProductGroup(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'ProductGroup' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'ProductGroup' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductGroupIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.ProductGroup obj = dod.getRandomProductGroup();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'ProductGroup' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.ProductGroup.findProductGroup(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'ProductGroup' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.ProductGroup.findProductGroup(id));
    }
    
}
