// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.geshotel.resto.domain;

import org.adorsys.geshotel.resto.domain.SaleItemDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SaleItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SaleItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SaleItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SaleItemIntegrationTest: @Transactional;
    
    @Autowired
    private SaleItemDataOnDemand SaleItemIntegrationTest.dod;
    
    @Test
    public void SaleItemIntegrationTest.testCountSaleItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", dod.getRandomSaleItem());
        long count = org.adorsys.geshotel.resto.domain.SaleItem.countSaleItems();
        org.junit.Assert.assertTrue("Counter for 'SaleItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SaleItemIntegrationTest.testFindSaleItem() {
        org.adorsys.geshotel.resto.domain.SaleItem obj = dod.getRandomSaleItem();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.SaleItem.findSaleItem(id);
        org.junit.Assert.assertNotNull("Find method for 'SaleItem' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'SaleItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SaleItemIntegrationTest.testFindAllSaleItems() {
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", dod.getRandomSaleItem());
        long count = org.adorsys.geshotel.resto.domain.SaleItem.countSaleItems();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'SaleItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.adorsys.geshotel.resto.domain.SaleItem> result = org.adorsys.geshotel.resto.domain.SaleItem.findAllSaleItems();
        org.junit.Assert.assertNotNull("Find all method for 'SaleItem' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'SaleItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SaleItemIntegrationTest.testFindSaleItemEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", dod.getRandomSaleItem());
        long count = org.adorsys.geshotel.resto.domain.SaleItem.countSaleItems();
        if (count > 20) count = 20;
        java.util.List<org.adorsys.geshotel.resto.domain.SaleItem> result = org.adorsys.geshotel.resto.domain.SaleItem.findSaleItemEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'SaleItem' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'SaleItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SaleItemIntegrationTest.testFlush() {
        org.adorsys.geshotel.resto.domain.SaleItem obj = dod.getRandomSaleItem();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.SaleItem.findSaleItem(id);
        org.junit.Assert.assertNotNull("Find method for 'SaleItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySaleItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'SaleItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaleItemIntegrationTest.testMerge() {
        org.adorsys.geshotel.resto.domain.SaleItem obj = dod.getRandomSaleItem();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.SaleItem.findSaleItem(id);
        boolean modified =  dod.modifySaleItem(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.adorsys.geshotel.resto.domain.SaleItem merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'SaleItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SaleItemIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", dod.getRandomSaleItem());
        org.adorsys.geshotel.resto.domain.SaleItem obj = dod.getNewTransientSaleItem(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'SaleItem' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'SaleItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SaleItemIntegrationTest.testRemove() {
        org.adorsys.geshotel.resto.domain.SaleItem obj = dod.getRandomSaleItem();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'SaleItem' failed to provide an identifier", id);
        obj = org.adorsys.geshotel.resto.domain.SaleItem.findSaleItem(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'SaleItem' with identifier '" + id + "'", org.adorsys.geshotel.resto.domain.SaleItem.findSaleItem(id));
    }
    
}
